### ISSUE TITLE
Offline Mode: Kernel Panic, when no known SSID is present

### ISSUE THREAD

**Issue by kumzugloom** [avanc/photOS#104]
The readme quotes: 

> **Offline**: Works also if no internet connection is available.

However, if no already known SSID is present, my device is forced into eternal reboots due to kernel panics. Is there any documentation on how to achieve the offline mode?

**Comment by kumzugloom** [comment]
In case anyone else wonders:
According to [this ](https://github.com/ccrisan/thingos/wiki/netwatch.conf) you can deactivate automatic reboot on unavailable WiFi Connection by changing /etc/watch.conf
from 

> LINK_WATCH="true"

 to 

> LINK_WATCH="false"

**Comment by avanc** [comment]
@kumzugloom Sorry that I had no time to respond. Thanks for the details, I added it into the documentation: https://github.com/avanc/photOS/wiki/FAQ#how-to-avoid-reboots-if-network-connection-is-not-working
