### ISSUE TITLE
Lightning bolt icon on top right corner

### ISSUE THREAD

**Issue by lanzer** [avanc/photOS#122]
The picture frame always show a lightning bolt icon on the top right corner, and I don't want that to cause burn-in on my monitor.  Is there a way to remove it in config?  If not, can somone point me to where the image file is located, or where in code that image is loaded?

**Comment by chr2k** [comment]
Do you use a RaspberryPi? I know this icon if you use a RPi without the right power supply.

**Comment by lanzer** [comment]
Thank you! I had no idea. :)  I'll switch out the power supply.

Closing this ticket as it's completely off topic.
