### ISSUE TITLE
error: the server does not support locks mount.davfs

### ISSUE THREAD

**Issue by Schimy** [avanc/photOS#123]
Hi, I have installed photOS on an RPi 2 and created a new user on my Nextcloud and shared a directory for the photos. 
When integrating via WebDAV, I now get the following error message:

`Mounting https://<url-to-my-nextcloud>/remote.php/dav/files/<user>/<share> failed: mount.davfs: the server does not support locks mount.davfs: Mounting failed. 404 Not Found
`

Can anyone here help me and tell me what I am doing wrong?

many thx and so long,
schimy

**Comment by ssanikovich** [comment]
The same issue

**Comment by avanc** [comment]
Hm, I searched a little bit for this error message, could not find much.
There seems to be an app available: https://github.com/nextcloud/server/issues/1308
But I didn't installed any additional apps on my instance and it is working as expected...

In addition, there shouldn't be a lock, as the files are only copied from source, but not modified...
https://wiki.archlinux.org/title/Davfs2#Creating/copying_files_not_possible_and/or_freezes

**Comment by Schimy** [comment]
had experimented a bit with fbi and davfs in the meantime. ... also a good project here: https://www.instructables.com/DIY-Raspberry-Pi-24-Digital-Picture-Photo-Frame/

then a fresh installation of photoos ... and now, everything runs out-of-the-box ... magic!
thx for the support
