### ISSUE TITLE
WebGUI stops working after message disappears (10 pictures)

### ISSUE THREAD

**Issue by Mathes75** [avanc/photOS#125]
Running a Raspi ZeroW I have the issue that the WebGUI can't be accessed after the message to the config page disappeared. All browsers I have tried show "Website not available". Bug or feature?

**Comment by avanc** [comment]
@Mathes75 this wasn't an issue caused by photOS?

**Comment by Mathes75** [comment]
Hi @avanc - right. I don't know where it came from, but it was resolved after a few reboots.
