### ISSUE TITLE
SSH  Connection do not work

### ISSUE THREAD

**Issue by mrlaja** [avanc/photOS#23]
How can i find Out the SSH User and Password?

**Comment by mrlaja** [comment]
OK. Admin and no Password

**Comment by mrlaja** [comment]
Root and no password

**Comment by avanc** [comment]
Hope you didn't spend too much time finding the answer.
I updated the FAQ: https://github.com/avanc/photOS/wiki/FAQ#what-are-the-ssh-credentials-username-and-password
