### ISSUE TITLE
Images are deleted at reboot

### ISSUE THREAD

**Issue by mrlaja** [avanc/photOS#26]
I uploaded some Pictures to /pictureframe/local Images/  via filezilla, because i dont have an webdav folder.
But at reboot any Image ist deleted. There should be a folder for Pictures, wich should stay Always in the frame.

**Comment by avanc** [comment]
The webdav is just a one-way sync, i.e. new files are copied onto the device and all file available on the remote side are removed locally. So you should not configure a webdav server with an empty folder as this would remove all files on the device.
Does this apply for you?

If there is no webdav configuration (no /data/photoframe/conf/webdav.conf on photOS >=0.3.0) the files stay on the device in my case. However, there will be an (annoying in your case) information on how to configure photOS.
I'll have a look how this can be handled better.
