### ISSUE TITLE
do not Shuffle 

### ISSUE THREAD

**Issue by admindonkey** [avanc/photOS#30]
Hi,

is it possible not to shuffle the images?
I'd like to show them one after the oher.

Greetings

**Comment by avanc** [comment]
I'm going to add a configuration parameter to show images in alphabetical order.

**Comment by avanc** [comment]
New release is in preparation. Documentation is updated: https://github.com/avanc/photOS/wiki/FAQ#how-do-i-deactivate-photo-shuffling
