### ISSUE TITLE
Missing support for *.jpeg

### ISSUE THREAD

**Issue by marcelpauly** [avanc/photOS#39]
JPG images with the filename extension *.jpeg instead of *.jpg are not displayed. At the moment you have to rename them manually to get them displayed on the screen.

**Comment by avanc** [comment]
Thanks for the hint. Will be included in the next release.

**Comment by avanc** [comment]
@marcelpauly You may want to test the prerelease, as it supports .jpeg now:
https://github.com/avanc/photOS/releases/tag/v0.3.4-rc1

But you can also wait for the stable release.
