### ISSUE TITLE
video (and picture) data format

### ISSUE THREAD

**Issue by ts617284** [avanc/photOS#48]
I tried to find it in documentation, but with no luck. So either it's not there or I am to dumb... (both is possible ;-) )

@avanc : Could you describe (or update documentation), which data format/codec for videos is allowed? Like mp4 , mpeg, etc.   Maybe also for pictures (jpeg, png, etc.). 
Also how does video and delay of the slideshow work together? If I set a delay of 15sec, and then a video gets displayed: Will the next picuter/video in line will also be displayed after 15sec? Or directly after the end of the video, no matter its length?

Thanks again for answering and your great project!
Tim

**Comment by Schrigga** [comment]
The following formats are currently supported:
- images: jpeg, png
- videos: mp4, mov

Currently the delay does not affect videos. They will play in full. 
There is currently a bug, when the video ends that the previous image will be displayed, while the next media is loaded.

**Comment by avanc** [comment]
I added the information to the [FAQ](https://github.com/avanc/photOS/wiki/FAQ#what-file-formats-are-supported)
