### ISSUE TITLE
CEC to wake up TV

### ISSUE THREAD

**Issue by timmmerlan** [avanc/photOS#50]
Hello,
thank you for this cool OS! I have successfully tried to turn on/off the HDMI connection from the web interface - which is no problem as long as the monitor (in my case a MEDION® LIFE® X15511 Smart-TV) is still turned on. However, although the TV should be CEC compliant to turn it on on HDMI input and CEC was activated, it did not react on the RasPi. Therefore, I wanted to ask if photOS brings CEC support with it and if yes, if there is any known issue about that having problems with some screen devices?
Thank you in advance for your support!

**Comment by avanc** [comment]
CEC is not currently supported by photOS (i.e. libcec not compiled). I started a testbuild to see what needs to be done.

**Comment by avanc** [comment]
Short update: There is a new pre-release (https://github.com/avanc/photOS/releases/tag/v0.3.6-rc1) with libcec included. Unfortunatelly, I forgot to update the version number so after update the webui still says it is version 0.3.5.

With this release I was able to manually turn the TV on/off:

* Get device number of the TV (usually 0)
  * `echo 'scan' | cec-client -s -d 1`
* Turn TV on
  * `echo 'on 0' | cec-client -s -d 1`
* Turn TV off
  * `echo 'standby 0' | cec-client -s -d 1`
* Get status of TV
  * `echo 'pow 0' | cec-client -s -d 1`
* Write message to OSD (in my case only 7 characters are shown 
  * `echo 'osd 0 hello' | cec-client -s -d 1`

More details can be found here: https://www.linuxuprising.com/2019/07/raspberry-pi-power-on-off-tv-connected.html

Now I'm making my mind on how to configure this in photOS.

**Comment by avanc** [comment]
Will be available in the next release and is already documented: https://github.com/avanc/photOS/wiki/FAQ#how-do-i-turn-a-cec-compatible-tv-onoff

**Comment by avanc** [comment]
@timmmerlan There is a new release candidate which includes CEC support:
https://github.com/avanc/photOS/releases/tag/v0.3.6-rc4

Would be great to get some feedback if it works as expected.
