### ISSUE TITLE
Audio OFF/ Ton bei Video ausschalten

### ISSUE THREAD

**Issue by Silber-Toaster** [avanc/photOS#55]
Hallo,
wie kann ich den Ton bei einem Video ausschalten?
Der Ton kommt über HDMI Signal in den Monitor. 

Hello,
how can I turn off the sound in a video?
The sound comes into the monitor via HDMI signal. 

Gruß Norman

**Comment by avanc** [comment]
You might try

    dtparam=audio=off

in /boot/config.txt

**Comment by Silber-Toaster** [comment]
Danke für dein Tip.
Aber leider hat es nicht geholfen.

Thanks for your tip.
But unfortunately it did not help.

**Comment by avanc** [comment]
You are right.

    hdmi_ignore_edid_audio=1

did the trick for me (https://www.raspberrypi.com/documentation/computers/config_txt.html#hdmi_ignore_edid_audio).
Let me know if it also works on your side, then I'm going to update the FAQ.

**Comment by Silber-Toaster** [comment]
Danke, das war die Lösung, nun funtoniert es. :)

Thanks, that was the solution, now it works. :)

**Comment by avanc** [comment]
Documentation updated: https://github.com/avanc/photOS/wiki/FAQ#how-to-deactivate-audio-output-via-hdmi
