### ISSUE TITLE
Add animated GIF Support

### ISSUE THREAD

**Issue by escuco** [avanc/photOS#6]
It would be nice, if PhotOS would support animated GIF files. Thus, for example, 'video' loops and cinemagraphs could be played on the photo frame.
Examples: 
http://cinemagraphs.com/
https://www.gallereplay.com/

**Comment by avanc** [comment]
* [giflib](http://giflib.sourceforge.net/)
    * was used by fbv
    * not sure if it supports animations: http://giflib.sourceforge.net/whatsinagif/animation_and_transparency.html

**Comment by escuco** [comment]
Did some testing with graphic output (spec. animated gif) on framebuffer:

fbi -> only shows the first frame from the animated gif
fim -> only shows the first frame from the animated gif
feh -> doesn't support framebuffer

gif_play -> got stuck while compiling due to missing dependencies and other error messages ¯\_(ツ)_/¯

**Comment by escuco** [comment]
Maybe playing cinemagraph video files is an option instead of animated gifs:

All players are tested with mp4 no audio cinemagraphs with 1920x1080 pixel resolution

[mplayer](https://mplayerhq.hu/) -> to slow on raspberry pi zero

[vlc](https://www.videolan.org/vlc/) -> works nice
`vlc --no-video-title --fbdev /dev/fb1 filename.mp4`

[omxplayer](https://github.com/popcornmix/omxplayer) (command line video player for raspberry pi) -> works nice
`omxplayer -b filename.mp4`

**Comment by Schrigga** [comment]
I have created a pull request which adds video support

**Comment by escuco** [comment]
So from my point of view, this issue could be closed. The video support works quite well and with it, there's no longer need for gif support.

**Comment by avanc** [comment]
That's true.
