### ISSUE TITLE
manually control slide show

### ISSUE THREAD

**Issue by chrgachrga** [avanc/photOS#63]
Hi,
i saw the new feature in 0.3.6 of manually controlling the slide show with physical buttons via GPIO.
Is there documentation on that? The buttons are very interesting.
In addition I am using ioBroker for home automation quite a bit.
I would be interested in understanding the technical implementation to be able to control the slide show also via the home automation, to (for example) implement a solution to be able to control the slide show with a remote from IKEA or similar.
These are just examples, but surely first I need to understand how the buttons are implemented.
Is there documentation on that already?
Happy to share the ioBroker implementation, once I am done.

Thanks
chrga

**Comment by avanc** [comment]
Regarding your second question I created the following ticket: https://github.com/avanc/photOS/issues/64

Unfortunately, this needs some architectural changes which I would plan for 2.0, which includes a rewrite of the shell scripts to Python.

**Comment by chrgachrga** [comment]
ok, thanks.
I see what you are saying: the next/prev is directly linked to the GPIO and no API call is in-between for now!?
That limits the options for external access.
Would a batch script work that simulates the GPIO change? I could then try to run the script from remote!?

**Comment by Schrigga** [comment]
> I created a very short explanation: https://github.com/avanc/photOS/wiki/Control-slideshow-using-physical-buttons I'm currently not sure if the Raspberry Pi provides internal pull-up/pull--down resistors or if they have to be added in additional. @Schrigga What is your experience?

The raspberry pi has internal resistors (1.8kOhm) which needs to be enabled. I have used additional resistors (10kOhm).

**Comment by avanc** [comment]
Closed in favor of https://github.com/avanc/photOS/issues/64
