### ISSUE TITLE
manual buttons not working

### ISSUE THREAD

**Issue by chrgachrga** [avanc/photOS#67]
Hi,
I was checking on the new feature for physical buttons. My conf looks as follows:
GPIO_PIN_NEXT=5
GPIO_PIN_PREVIOUS=6
GPIO_PIN_PLAY=0
GPIO_ACTION_VALUE=0
SLIDESHOW_DELAY=10

If I now add a button between 3.3v and GPIO 5 or 6, nothing happens.
I am on a raspberry pi 2.
Setup is done according to this:
https://www.elektronik-kompendium.de/sites/raspberry-pi/2110081.htm

Can you confirm that the config and button is right? Or am I missing anything?

thanks,
chrga

**Comment by universalappfactory** [comment]
Hi,

I have prettry the same config and it works for me with a rasperry pi zero. Have you set GPIO_ACTION_VALUE according to your setup (pullup or pulldown resistor)?

And you may check this output in your console:
cat /sys/class/gpio/gpio6/value

there you should see if the button is pressed or not (press the button and run the command)

**Comment by universalappfactory** [comment]
Ah and I think there is an error in the is_gpio_pressed function.

if [ "$(cat /sys/class/gpio/gpio${GPIO_PIN_NEXT}/value)" -eq "${GPIO_ACTION_VALUE}" ] 

should be

if [ "$(cat /sys/class/gpio/gpio${1}/value)" -eq "${GPIO_ACTION_VALUE}" ]

I think.

**Comment by avanc** [comment]
@universalappfactory Thanks for pointing that out.

**Comment by avanc** [comment]
@chrgachrga I fixed the issue emntioned by @universalappfactory. However, I#M not sure if this is your issue, as _something_ should happen also with the bug. Please reopen with additional information if needed.
