### ISSUE TITLE
different Wi-Fi networks - Documentation

### ISSUE THREAD

**Issue by cs301cs301** [avanc/photOS#73]
If you need more Wi-Fi networks, then add `priority=xx` to the `wpa_supplicant.conf`. Highest priority is choosen first.

```
network={
      ssid="YourSSID1"
      psk="YourPSK"
      priority=100
}
network={
      ssid="YourSSID2"
      psk="YourPSK"
      priority=99
}
network={
      ssid="YourSSID3"
      psk="YourPSK"
      priority=80
}
```

I use this config.
SSID1 is my smartphone hotspot, SSID2 is the standard WIFI of the end user and SSID3 my network at home. 
If i need to change some settings, then you can start your hotspot, and connect to the photoframe, after power off/on.

**Comment by avanc** [comment]
Very interesting, I didn't knew it. Thanks for the hint!
I updated the wiki: https://github.com/avanc/photOS/wiki/Wifi
