### ISSUE TITLE
Sync frequency

### ISSUE THREAD

**Issue by timmmerlan** [avanc/photOS#85]
Hello,
asking just because interested: How often (and at certain timestamps?) does photOS usually sync with the WebDAV server?
Best regards,
Tim

**Comment by escuco** [comment]
Hi Tim,

the sync is running at startup and then every half hour:
[https://github.com/avanc/photOS/wiki/FAQ#how-are-photos-downloaded](https://github.com/avanc/photOS/wiki/FAQ#how-are-photos-downloaded)

**Comment by timmmerlan** [comment]
Thank you for the quick answer - sorry for the question, I somehow didn't see that in the FAQs...
