### ISSUE TITLE
Raspberry Pi Zero W (v. 1)

### ISSUE THREAD

**Issue by Surfer2010** [avanc/photOS#89]
Is it possible, and if, which image should I use, to have this system run on a raspberry pi zero w (first generation)

Thanks für the support, great work you did!!!!

**Comment by avanc** [comment]
Yes, you can use the Raspberry Pi 1 image:
https://github.com/avanc/photOS/releases/download/v0.3.7/photOS-raspberrypi-0.3.7.img.xz
